### ISSUE TITLE
JSON instructions unclear 

### ISSUE THREAD

**Issue by ThatOneCalculator** [ashisbored/disrev#1]
From the README:

## Configuration (new, multi-channel mode)

Use a JSON-based config file for multi channel mode:
```json
{
    "discord_to_revolt": {
        "xxx": "xxx"
    },
    "revolt_to_webhook": {
        "xxx": "https://discord.com/api/webhooks/xxx/xxx"
    }
}
```

What are all the xxx's supposed to be? It's very confusing what each "xxx" represents.

**Comment by ashhhleyyy** [comment]
Ah, I thought that would be implied that they were the channel IDs from Discord and revolt. I'll update the README to explain what each one is

**Comment by ashhhleyyy** [comment]
Hopefully that clears up the confusion, if anything still doesn't make sense, feel free to add a comment here and I'll have a look

**Comment by ThatOneCalculator** [comment]
Yea, that's way clearer. Thank you!
