### ISSUE TITLE
Please set the envrionment variable [and then my revolt bot's token here]

### ISSUE THREAD

**Issue by vague-advice** [ashisbored/disrev#3]
not sure whats causing this, any ideas?
![image](https://user-images.githubusercontent.com/87152885/165630415-f99edbc6-ea99-4edc-ae63-739c3277abca.png)

i'm trying to use disrev in single channel mode, ive got the webhook & everything setup but poetry / disrev gives me this error
```Please set the envrionment variable [my revolt bot token here]```

**Comment by ashhhleyyy** [comment]
You aren't meant to edit the `config.py` file directly, you should instead revert your changes and create a `.env` file with contents like this:
```
REVOLT_TOKEN=<your token here>
DISCORD_TOKEN=<your token here>
```

**Comment by vague-advice** [comment]
ah, so should the new ```.env``` file be named ```config.env```?

**Comment by ashhhleyyy** [comment]
nope, just `.env`

**Comment by vague-advice** [comment]
okay, i'll try this and let you know

**Comment by vague-advice** [comment]
sorry, one more question: in the ```.env``` file i'm supposed to include the discord channel id, webhook and revolt channel id, along with the tokens, right?

**Comment by ashhhleyyy** [comment]
Nope, the channel mappings should go in a `json` file (eg. `config.json`) which you then pass in as an argument, which is shown here: https://github.com/ashhhleyyy/disrev#configuration-new-multi-channel-mode

**Comment by vague-advice** [comment]
it worked! thanks for your help

PS: as mentioned in issue #2, is there a fix for messages from revolt to discord?
